services:
  mongodb:
    container_name: mongodb-8.2
    image: docker.io/mongodb/mongodb-community-server:8.2-ubi8
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: passsword

    volumes:
      - data:/data/db
    ports:
      - 27017:27017
  
  mongo-init:
    image: docker.io/mongodb/mongodb-community-server:8.2-ubi8
    depends_on:
      - mongodb
    command: >
      bash -c "sleep 5 && mongosh --host mongodb:27017 --eval \"try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'mongodb:27017' } ]}) }\""
    restart: "no"
  
volumes:
  data:

networks:
  default:
    external: true
    name: base